@startuml
actor Utente_registrato
participant ContactsbookViewController
participant ModifyViewController
participant "Contatto" as Contact
participant DuplicateContactViewController
participant Database


Utente_registrato -> ContactsbookViewController: actionModify
activate ContactsbookViewController
ContactsbookViewController->ModifyViewController: setObservableList
activate ModifyViewController
ContactsbookViewController->ModifyViewController: setContact
ModifyViewController -> ModifyViewController: actionModify
ModifyViewController->Contact: new
activate Contact
Contact-->ModifyViewController: contact
deactivate Contact
ModifyViewController->ModifyViewController: contains
alt Contatto duplicato
    ModifyViewController -> DuplicateContactViewController
    activate DuplicateContactViewController
    DuplicateContactViewController-->ModifyViewController
    ModifyViewController->DuplicateContactViewController: getBoolean
    deactivate DuplicateContactViewController 
        alt true
            ModifyViewController->ModifyViewController:remove
            ModifyViewController->ModifyViewController:add
            ModifyViewController-->Database: modifyContact
            activate Database
            loop 3
             Database -> Database: formattaOut
            end 
            Database -> Database: executeUpdate
            Database --> ModifyViewController
            deactivate Database
        else false
            ModifyViewController->ModifyViewController:show
        end
else Contatto non duplicato
ModifyViewController->ModifyViewController: remove
ModifyViewController->ModifyViewController: add
ModifyViewController-->Database: modifyContact
activate Database
            loop 3
             Database -> Database: formattaOut
            end 
            Database -> Database: executeUpdate
            Database --> ModifyViewController
            deactivate Database
end
activate Database
deactivate ModifyViewController
deactivate Database
ModifyViewController-->ContactsbookViewController
deactivate ContactsbookViewController
@enduml 