@startuml
actor Utente
participant ContactsbookViewController
participant ModifyViewController
participant "Contatto" as Contact
participant UserInteractionDataInterface


Utente -> ContactsbookViewController: actionModify
activate ContactsbookViewController
ContactsbookViewController->ModifyViewController: setContact
activate ModifyViewController
ModifyViewController -> ModifyViewController: actionModify
ModifyViewController->Contact:new
activate Contact
Contact-->ModifyViewController:contact
deactivate Contact
ModifyViewController-->ContactsbookViewController: contact
deactivate ModifyViewController
ContactsbookViewController->ContactsbookViewController: actionDelete
ContactsbookViewController->ContactsbookViewController: actionAdd
ContactsbookViewController->UserInteractionDataInterface: modifyContact
activate UserInteractionDataInterface
deactivate UserInteractionDataInterface
deactivate ContactsbookViewController
@enduml 