@startuml
actor Utente
participant "LoginViewController" as LoginViewController
participant "App" as App 
participant "Database" as db

Utente -> LoginViewController: run()

alt actionLoginLocal()
LoginViewController -> App: setRoot("ContactsbookView")
activate App
deactivate App
else actionLogin()

activate db
activate LoginViewController
LoginViewController -> db: new()
LoginViewController -> db: ConnectionDB()
db --> LoginViewController

LoginViewController -> db: checkLogin()
db --> LoginViewController
deactivate db
opt checkLogin()==true
LoginViewController -> App: setRoot("ContactsbookView")
activate App
deactivate App
deactivate LoginViewController
end



end





@enduml
