@startuml
actor Utente
participant "UserInteracionDataInterface" as user
participant "LoginViewController" as LoginViewController
participant "App" as App 
participant "Database" as db

Utente -> user: login()
activate user

alt loginLocal
user -> LoginViewController: actionLoginLocal()
activate LoginViewController
LoginViewController -> App: setRoot("ContactsbookView")
activate App
deactivate App
deactivate LoginViewController

else else
user-> LoginViewController: actionLogin()
activate LoginViewController
LoginViewController -> db: new()
activate db
LoginViewController -> db: ConnectionDB()
db --> LoginViewController
LoginViewController -> db: checkLogin()
db --> LoginViewController: controllo
deactivate db
alt controllo==true
LoginViewController -> App: setRoot("ContactsbookView")
activate App
deactivate App
else else
LoginViewController --> user: messageError()
deactivate 
end

activate App
deactivate App
deactivate LoginViewController
deactivate user


end





@enduml
