@startuml
actor Utente_non_registrato
participant LoginViewController
participant  Database

Utente_non_registrato->LoginViewController:run()
activate LoginViewController
LoginViewController -> Database: new()
LoginViewController -> Database: ConnectionDB()
Database --> LoginViewController: Connection

activate Database
alt btnSingin is abilitato
Utente_non_registrato->LoginViewController:actionSignin
LoginViewController -> Database: insertUser 


 Database -> Database: executeUpdate

Database --> LoginViewController
end

@enduml
