@startuml
actor Utente_registrato
participant ContactsbookViewController
participant ModifyViewController
participant "Contatto" as Contact
participant DuplicateContactViewController
participant UserInteractionDataInterface


Utente_registrato -> ContactsbookViewController: actionModify
activate ContactsbookViewController
ContactsbookViewController->ModifyViewController: setObservableList
activate ModifyViewController
ContactsbookViewController->ModifyViewController: setContact
ModifyViewController -> ModifyViewController: actionModify
ModifyViewController->Contact: new
activate Contact
Contact-->ModifyViewController: contact
deactivate Contact
ModifyViewController->ContactsbookViewController: contains
ContactsbookViewController-->ModifyViewController
alt Contatto duplicato
    ModifyViewController -> DuplicateContactViewController: set
    activate DuplicateContactViewController
    DuplicateContactViewController-->ModifyViewController
    deactivate DuplicateContactViewController 
        alt Aggiungi
            ModifyViewController->ModifyViewController:remove
            ModifyViewController->ModifyViewController:add
            ModifyViewController-->UserInteractionDataInterface: modifyContact
        else Modifica
            ModifyViewController->ModifyViewController:show
        end
else Contatto non duplicato
ModifyViewController->ModifyViewController: remove
ModifyViewController->ModifyViewController: add
ModifyViewController-->UserInteractionDataInterface: modifyContact
end
activate UserInteractionDataInterface
deactivate ModifyViewController
deactivate UserInteractionDataInterface
ModifyViewController-->ContactsbookViewController
deactivate ContactsbookViewController
@enduml 