@startuml
actor Utente_registrato
participant ContactsbookViewController
participant AddViewController
participant "Contatto" as Contact
participant DuplicateContactViewController
participant UserInteractionDataInterface

Utente_registrato -> ContactsbookViewController: actionAdd
activate ContactsbookViewController
ContactsbookViewController->AddViewController: setObservableList
activate AddViewController
AddViewController -> AddViewController: actionAdd
AddViewController -> Contact: new
activate Contact
Contact->Contact: new(txtName, txtSur)
opt Numero di telefono presente
    Contact -> Contact: addNumber
end
opt Email presente
    Contact -> Contact: addEmail
end
Contact --> AddViewController
deactivate Contact
AddViewController->ContactsbookViewController: contains
ContactsbookViewController-->AddViewController

alt Contatto duplicato
    AddViewController -> DuplicateContactViewController: set
    activate DuplicateContactViewController
    DuplicateContactViewController-->AddViewController
    deactivate DuplicateContactViewController 
        alt Aggiungi
            AddViewController->AddViewController:add
            AddViewController-->UserInteractionDataInterface: insertContact
        else Modifica
            AddViewController->AddViewController:show
        end
else Contatto non duplicato
AddViewController->AddViewController: add
AddViewController-->UserInteractionDataInterface: insertContact
end
deactivate Contact
AddViewController-->ContactsbookViewController
deactivate AddViewController
deactivate ContactsbookViewController
@enduml 